version: "3"
services:
  scorm-player-db:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=scorm-player
      - MONGO_INITDB_ROOT_PASSWORD=...
    image: mongo:5.0
    restart: always
    volumes:
      - ./data/db:/data/db
  scorm-player-api:
    depends_on:
      - scorm-player-db
    environment:
      - FLUX_SCORM_PLAYER_API_DATABASE_PASSWORD=...
    image: docker-registry.fluxpublisher.ch/flux-scorm-player/api:latest
    restart: always
    volumes:
      - ./data/scorm:/scorm
  other-service:
    depends_on:
      - scorm-player-api
    environment:
      [- FLUX_SCORM_PLAYER_API_HOST=scorm-player-api]
      [- FLUX_SCORM_PLAYER_API_PORT=9501]
